
name: Update README2

on:
  schedule:
    - cron: '0 */24 * * *' # Cada 12 horas

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update README with recent activity
        uses: your-username/repository-name@main # 
